### ISSUE TITLE
Implement the application with accessibility in mind

### ISSUE THREAD

**Issue by juliosampaio** [ifactory-solutions/inside-client#18]
Guys, as this is an open source project I think we should keep accessibility in mind when developing the whole app, mainly the frontend. Providing users with accessibility options widens the potential audience of the software, and should exist as a common practice in all software design and production. What are your thoughts about this topic?

**Comment by jourdanrodrigues** [comment]
I think we should consider this mandatory due to the social responsibility. In a first glance, what I suggest we pay attention:

- [Spectrum](https://chrome.google.com/webstore/detail/spectrum/ofclemegkcmilinpcimpjkfhjfgmhieb) (color blindness simulator);
- [ARIA](https://developer.mozilla.org/pt-BR/docs/Web/Accessibility/ARIA);
- [SEO](https://en.wikipedia.org/wiki/Search_engine_optimization) (_screen readers_ and _search engines_ are basically the same).

I'll put more about the subject as I remember.

For the ones that have never heard or worked with accessibility, is not much complicated than learning a new code pattern.
