### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-client#21]

**Comment by jourdanrodrigues** [comment]
What will we use for it? I can speak about [Travis](https://travis-ci.org/) and heard about [CircleCI](https://circleci.com/) (but it seems limited).

I can send a pull request with Travis in a few moments.

--- Edit ---

Also, in order to attend this feature, would be good (or even needed) adding the ["engines" section](https://docs.npmjs.com/files/package.json#engines) to the "package.json".

I'm bringing this up because we need to explicitly define the environment of the app for this CI case and, very soon, for hosting in a IaaS/PaaS.
